version: '3.3'

services:
  backend:
    image: pitohu/eco-view:eco-view-server
    ports:
      - 3000:3000

  frontend:
    image: pitohu/eco-view:eco-view-client
    ports:
      - 80:8080
    depends_on:
      - backend